# API Calls
import requests
from urllib import parse


# Integrate this dataset using cURL (from the bottom of https://data.nationalgrideso.com/ancillary-services/dynamic-containment-data#)
# # Get a list of dataset's resources
# curl -L -s https://data.nationalgrideso.com/ancillary-services/dynamic-containment-data/datapackage.json | grep path
#
# # Get resources
# curl -L https://data.nationalgrideso.com/backend/datastore/dump/6fd8e042-be27-4c67-ad59-5acdd2a7b0fd
#
# curl -L https://data.nationalgrideso.com/backend/datastore/dump/26aefbcc-fce0-403f-80e1-4a26af3fe84b
#
# curl -L https://data.nationalgrideso.com/backend/datastore/dump/ddc4afde-d2bd-424d-891c-56ad49c13d1a
#
# curl -L https://data.nationalgrideso.com/backend/datastore/dump/888e5029-f786-41d2-bc15-cbfd1d285e96
#
# curl -L https://data.nationalgrideso.com/backend/dataset/aca07dcb-f807-409c-a4ec-da5dc052b8ba/resource/0b8dbc3c-e05e-44a4-b855-7dd1aa079c68/download/dynamic_containment_masterdata.csv

# Explore resources
# URL = "https://data.nationalgrideso.com/ancillary-services/dynamic-containment-data/datapackage.json"
# r = requests.get(URL)
# r.json()
#
# for src in r.json()['resources']:
#     print(f"{src['name']}: {src['path']}")

import datetime
from pprint import pprint

def fetch_todays_results():
    ''' Quick and dirty api call using the example code
        generated by the query builder (with my date modification) so I can
        get data flowing and rough out the rest.
    '''
    today_date_str = datetime.datetime.now().strftime("%Y-%m-%d")
    tomorrow = datetime.datetime.now() + datetime.timedelta(days=1)
    tomorrow_str = tomorrow.strftime("%Y-%m-%d")
    # Define api params
    sql_query =  f'''SELECT COUNT(*) OVER () AS _count, * FROM "ddc4afde-d2bd-424d-891c-56ad49c13d1a" WHERE "Company" = 'HABITAT ENERGY LIMITED' AND "EFA Date" >= '{today_date_str}T00:00:00.000Z' AND "EFA Date" < '{tomorrow_str}T00:00:00.000Z' ORDER BY "_id" ASC LIMIT 100'''
    params = {'sql': sql_query}
    # Query the api
    try:
        response = requests.get('https://api.nationalgrideso.com/api/3/action/datastore_search_sql', params = parse.urlencode(params))
        data = response.json()["result"]
        print("Received:")
        pprint(data) # Printing data
    except requests.exceptions.RequestException as e:
        print(e.response.text)
    return response.json()["result"]["records"]
